
import StoreProvider from '@/store/StoreProvider'
import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import '../styles/globals.css'

const montserrat = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Country App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${montserrat.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </StoreProvider>

  )
}
